# open_library_tests/
#     config/
#         __init__.py
#         config.py
#     api/
#         __init__.py
#         lists_api.py
#     pages/
#         __init__.py
#         base_page.py
#         lists_page.py
#     objects/
#         __init__.py
#         list_object.py
#     tests/
#         __init__.py
#         conftest.py
#         test_lists_api.py
#     utils/
#         __init__.py
#         logger.py
#     requirements.txt
#     pytest.ini
